### PR TITLE
'Balance' and 'PSCAD compilers' tabs removed

### PR DESCRIPTION
**Pull request by CVLenerginet**
'Balance' and 'PSCAD compilers' tabs removed.
Default model-specific information alligned as (previously two different examples, this and Aadum):
image

### CODE REVIEW

**Comment by matbkri** [comment]
List of available compilers should not be removed. It is relevant for externals to see supported compilers. Serverlist should be.

**Review by matbkri — CHANGES_REQUESTED** [review]
Compilerlist should not be removed yet. It is very relevant for externals too be able to see supported compilers.

**Comment by CVLenerginet** [comment]
New commit added to the branch. "PSCAD compilers" tab is reinserted.

**Comment by CVLenerginet** [comment]
New commit added with final changes. 

> 3rd times a charm :^)

**Review by matbkri — APPROVED** [review]

**Pull request merged**
